version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
  - netstandard
  - develop
dotnet_csproj:
  patch: true
  file: '**\Krypt.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - git config --global core.autocrlf true
# set clone depth
clone_depth: 5 
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - dotnet --version
  # Display minimal restore text
  - dotnet restore ./src/Krypt.sln --verbosity m
build_script:
  - dotnet pack ./src/Krypt/Krypt.csproj --include-source --include-symbols --configuration Release
test_script:
  # restore packages for our unit tests
  # - dotnet restore ./src/Krypt.Test.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - dotnet test ./src/Krypt.Test/Krypt.Test.csproj
deploy:
  provider: NuGet
  name: production
  on:
    branch: master
  api_key:
    secure: lvyCj7LQWuEq//G7DuoqV8VHKshnrlGdULqs9WinPEt297+6u2c5tHjIiRavHqxD
  skip_symbols: false
  artifact: /.*\.nupkg/
after_build:
  # For once the build has completed
on_finish :
  # any cleanup in here