version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
  - develop
environment:
  codecov_apikey:
    secure: kwGF/Xd38DP8DGLzBOvX1xaSa+hUeCGV9prpnw79L3wtC4i9ivfGkhvKfANTUWiq
dotnet_csproj:
  patch: true
  file: '**\Krypt.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
cache:
- '%USERPROFILE%\.nuget\packages'
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - git config --global core.autocrlf true
# set clone depth
clone_depth: 5 
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - dotnet --version
  # Display minimal restore text
  - dotnet restore ./src/Krypt.sln --verbosity m
build_script:
  - if [%APPVEYOR_REPO_BRANCH%]==[master] dotnet pack ./src/Krypt/Krypt.csproj --nobuild --include-source --include-symbols --configuration Release else dotnet pack ./src/Krypt/Krypt.csproj --nobuild --include-source --include-symbols --configuration Release --version-suffix "-beta"
test_script:
  # restore packages for our unit tests
  # run the unit tests (requires changing into the test directory) Require coverlet for coverage calculation
  - dotnet test ./src/Krypt.Test/Krypt.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_test:
- ps: >-
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh

    bash codecov.sh -f "./src/Krypt.Test/coverage.xml" -t %codecov_apikey%
deploy:
  - provider: NuGet #support regular commit to master
    name: production
    on:
      branch: master
  - provider: NuGet #support tags
    name: production
    on:
        appveyor_repo_tag: true
  - api_key:
    secure: Md9Vp7ciqXOXdcslNVOamwENnV+yvnfUUo72fq34WfnTeUND4WuLLdhMH68PLjP4
  - skip_symbols: false
  - artifact: /.*\.nupkg/
artifacts:
  - path: '**\*.nupkg' # find all NuGet packages recursively'
    name: krypt
    type: NuGetPackage
after_build:
  # For once the build has completed
on_finish :
  # any cleanup in here