version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: lvyCj7LQWuEq//G7DuoqV8VHKshnrlGdULqs9WinPEt297+6u2c5tHjIiRavHqxD
  skip_symbols: false
  artifact: /.*\.nupkg/